num_classes: 10
activation: LReLU
backbone: (
  (-1, 1, Conv, (64, 7, 2, 3)),
  (-1, 1, MP, (2, 2)),
  
  (-1, 1, Conv, (192, 3)),
  (-1, 1, MP, (2, 2)),
  
  (-1, 1, Conv, (128, 1)),
  (-1, 1, Conv, (256, 3)),
  (-1, 1, Conv, (256, 1)),
  (-1, 1, Conv, (512, 3)),
  (-1, 1, MP, (2, 2)),
  
  (-1, 4, Block,
  [
  (-1, 1, Conv, (256, 1)),
  (-1, 1, Conv, (512, 3)),
  ]),
  
  (-1, 1, Conv, (512, 1)),
  (-1, 1, Conv, (1024, 3)),
  (-1, 1, MP, (2, 2)),

  (-1, 2, Block,
  [
  (-1, 1, Conv, (512, 1)),
  (-1, 1, Conv, (1024, 3)),
  ]),

  (-1, 1, Conv, (1024, 3)),
  (-1, 1, Conv, (1024, 3, 2)),
  
  (-1, 1, Conv, (1024, 3)),
  (-1, 1, Conv, (1024, 3)),

  (-1, 1, Flatten),
  (-1, 1, FC, (4096)),
  (-1, 1, FC, )
)